kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sun
nodes:
- role: control-plane
  image: kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355
- role: worker
  image: kindest/node:v1.23.6@sha256:1af0f1bee4c3c0fe9b07de5e5d3fafeb2eec7b4e1b268ae89fcab96ec67e8355
networking:
  apiServerAddress: 192.168.0.104
  apiServerPort: 61000
